services:
  app:
    container_name: user_microservice
    build: .
    ports:
      - "5003:5003"
    depends_on:
      - user_postgres_db
    env_file:
      - .env.stage.docker

  user_postgres_db:
    container_name: postgres-user_db
    image: postgres:latest
    restart: always
    ports:
      - "9903:5432"
    env_file:
      - .env.stage.docker
    volumes:
      - pg_data:/var/lib/postgresql/data

  adminer:
    container_name: adminer-user_db
    image: adminer
    restart: always
    ports:
      - 8803:8080

volumes:
  pg_data:
